### PR TITLE
Generic Logger

### LINKED ISSUE #2: Generic Logger
We should replace the console.log with a generic logger interface to swap out any output. For example, using `debug` or `pino` or RPC calls to a logging server.

### PR DESCRIPTION
**Pull request by Redmega**
Resolves #2 

This would allow users to set their own logger function.

It is admittedly a fairly naive implementation. I welcome ideas on how we could improve it.

### CODE REVIEW

**Comment by Redmega** [comment]
If we wanted it to look neater we could convert the original implementation of debog into a class. Then you could instantiate a `new Debog(...)` and pass the settings as constructor args.

**Comment by tlackemann** [comment]
I think this aligns well with what I originally had in mind.

My original thought was to make some sort of `debog.logger` global that you could overwrite in the file.

```typescript
import debog from 'debog'

debog.logger = (message: string) => {
   // send to RPC server, debug, pino, etc.
}

@debog('methods')
```

The use of your init function I believe serves a similar purpose, simply set a global-type variable.

I am a bit more in favor of the above if not only because it eliminates the use to call an `init()` function. Thoughts?

Thanks for the pull request!

**Comment by Redmega** [comment]
@tlackemann Is that more what you had in mind?

**Comment by tlackemann** [comment]
@Redmega Code looks good, thanks for making the change!

The only thing missing is docs. If you'd like me to write those let me know and I can submit a quick commit before the end of the week.

**Comment by tlackemann** [comment]
Added docs and merging. Thanks for your contribution!

**Pull request merged**
