### PR TITLE
Feat/magic promises

### PR DESCRIPTION
**Pull request by Redmega**
Thought we could use some 🎩 magic 🐇 for handling promises. Makes the API cleaner imo, when the user doesn't need to worry about whether or not a function is async.

### CODE REVIEW

**Comment by Redmega** [comment]
Actually this will only work for native promises

https://gist.github.com/reggi/a1da4d0ea4f1320fa15405fb86358cff

**Comment by Redmega** [comment]
Alright, we short circuit for native promises with `instanceof Promise`, otherwise we use the Promise spec which states that `Promise.resolve(PromiseLike) === PromiseLike`. We can test any number of promises this way without needing to do something like check for the existence of `then()` (which could be faulty as the method may have `this.then` defined despite not being a promise. 🤷‍♂

**Comment by tlackemann** [comment]
Thanks for this!

One qualm, and it's something we'll need to weigh on, is the use of Bluebird which adds [26kb+](https://bundlephobia.com/result?p=bluebird@3.7.2) to the install size. Do we want to favor size and simplicity for functionality. Is there a lighter promise library we can utilize or does this cover all the cases that it's good enough?

All things considered, I love not having to specify a `*` before an async call, so magic is welcome

**Comment by Redmega** [comment]
It's a dev dependency, only used in the test. Shouldn't impact npm bundle size!

**Comment by Redmega** [comment]
Actually, I dug down into it, the overhead from removing __asyncTime saves us a lot of space, and bluebird is definitely not being added to the bundle

image

**Comment by tlackemann** [comment]
Very nice! Let's make some magic happen :tophat: :sparkles: 

Thank you for your contribution!

**Pull request merged**
